#!/bin/bash
printf "\n\n"
base64 -d <<< ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8CiAgICAgICAgICAgICAgICAgICAgICAgfCAgICBfXy1fXwogICAgICAgICAgICAgICAgICAgICBfXy1fXyAvICB8ICgKICAgICAgICAgICAgICAgICAgICAvICB8ICgoICAgfCB8CiAgICAgICAgICAgICAgICAgIC8oICAgfCB8fF9fX3xfLiAgLnwKICAgICAgICAgICAgICAgIC4nIHxfX198X3xgLS0tfC0nLicgKAogICAgICAgICAgICctLl8vX3wgKCAgIHxcICAgICB8LicgICAgXAogICAgICAgICAgICAgICAnLS5ffC4tLnwtLiAgICB8Jy0uX19fXycuCiAgICAgICAgICAgICAgICAgICB8LS0tLS0tLS0tLS0tLS0tLS0tJwogICAgICAgICAgICAgICAgICAgIGAtLS0tLS0tLS0tLS0tLS0tJyAgIA==
printf "\x1B[36m\n\nNow Searching the seas for your Port Number!\n\033[0m"



while true;
do
    sudo tcpdump -i any dst portrange 30000-31000 -q -n -c 25 -A >/tmp/SoT.txt 2>/dev/null
    port="sort -k 12 -u /tmp/SoT.txt | grep -Eo ".30...:" | cut -b 2,3,4,5,6"
    portnum=$(eval "$port")
    clear
    base64 -d <<< ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8CiAgICAgICAgICAgICAgICAgICAgICAgfCAgICBfXy1fXwogICAgICAgICAgICAgICAgICAgICBfXy1fXyAvICB8ICgKICAgICAgICAgICAgICAgICAgICAvICB8ICgoICAgfCB8CiAgICAgICAgICAgICAgICAgIC8oICAgfCB8fF9fX3xfLiAgLnwKICAgICAgICAgICAgICAgIC4nIHxfX198X3xgLS0tfC0nLicgKAogICAgICAgICAgICctLl8vX3wgKCAgIHxcICAgICB8LicgICAgXAogICAgICAgICAgICAgICAnLS5ffC4tLnwtLiAgICB8Jy0uX19fXycuCiAgICAgICAgICAgICAgICAgICB8LS0tLS0tLS0tLS0tLS0tLS0tJwogICAgICAgICAgICAgICAgICAgIGAtLS0tLS0tLS0tLS0tLS0tJyAgIA==
    printf "\x1B[36m"
    printf "\n\n\n Your port number is: \033[0m"
    printf "$portnum"
    sleep 1
done
